### ISSUE TITLE
I've fixed the API, got a Pull Request ready, need help passing a few tests.

### ISSUE THREAD

**Issue by lacymorrow** [bbraithwaite/omdb-client#1]
The url for the OMDB API now has an apikey parameter, which is breaking some of the tests that test `url` such as:
    `jsonHttp.getJson.calledWith(url, 3000).should.equal(true);`

**Comment by bbraithwaite** [comment]
Hey, 

Cool, thank you! 😃 

I had a quick look at the fork and with was able to get this test to pass with a quick tweak:

``` js
it('sets user defined timeout value', function(done) {
    var params = {
        title: 'Terminator',
        apiKey: 'foo',
        timeout: 3000
    };
    var url = 'http://www.omdbapi.com/?t=Terminator&api_key=foo&r=json&v=1';
    omdbApi.get(params, function() {
        jsonHttp.getJson.calledWith(url, 3000).should.equal(true);
        done();
    });
});
```

The tweak I made was to move this line further down to the end of the code that builds the URL string: https://github.com/lacymorrow/omdb-client/blob/master/lib/get.js#L83 and tweaked it to be:

``` js
if (params.apiKey) {
   query += '&api_key='.concat(params.apiKey);
}
```

I hope this helps/I've understood correctly? Feel free to open the PR if it would be easier to discuss the tweaks directly on the PR.

**Comment by lacymorrow** [comment]
That's perfect, cheers!

**Comment by lacymorrow** [comment]
Fixed and PR'd, thanks for your work!

**Comment by bbraithwaite** [comment]
Thank you, and thank you! 😄 I'll review the PR this week, update npm etc.
