### ISSUE TITLE
Publish updated version

### ISSUE THREAD

**Issue by lacymorrow** [bbraithwaite/omdb-client#3]
I've got some downstream code that relies on this package, but it hasn't worked since the key requirements were implemented.

This has been fixed in https://github.com/bbraithwaite/omdb-client/pull/2, please bump the version and republish to npm :)

**Comment by bbraithwaite** [comment]
Updated (finally). Sorry for the delay. Version 2.0.0 should include those changes.

https://www.npmjs.com/package/omdb-client

**Comment by lacymorrow** [comment]
🥇 Thanks so much!
